version: "3.8"

services:
  postgres:
    container_name: strive_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
